### ISSUE TITLE
EA does not import safMDG.xml

### ISSUE THREAD

**Issue by dbinev** [GfSE/SAF-EA-Profile#1] opened 2024-11-05 12:21 UTC
EA report errors and does not import:
![image](https://github.com/user-attachments/assets/8785b706-b263-43ab-a8a3-aaacda04d153)

**Comment by parkaneric** [comment] 2024-11-05 12:26
Hello, could you please provide some details such as your EA version (15, 16, 17) and the profile version (TdSE202x)?
Kind Regards

**Comment by dbinev** [comment] 2024-11-14 09:28
[Sparx EA]
version: 15.2.1560
version: 17.0.1703

[safMDG.xml]
TdS2022: both EA versions generate the same error
TdS2023: both EA versions generate the same error
TdS2024: both EA versions generate the same error

I was able to import (in both EA versions), activate and use only the [initial release ](https://github.com/GfSE/SAF-EA-Profile/releases/tag/Initial-Release) in the zip file.

**Comment by parkaneric** [comment] 2024-11-14 12:11
Thanks for the feedback!
That seems to be an interesting one - line 24 is the SAF logo as ASCII.
I will try to figure it out and will keep you up to date.

**Comment by jykahama** [comment] 2024-11-25 11:53
Same happened to me when tried do download the TdS2024.xml directly from file listing in main page (https://github.com/GfSE/SAF-EA-Profile/tree/TdSE2024)

If navigating into the file (https://github.com/GfSE/SAF-EA-Profile/blob/TdSE2024/safMDG.xml) and using download raw file button, the file gets downloaded properly.

**Comment by parkaneric** [comment] 2024-11-26 07:43
Thanks @jykahama!
I'll change the readme page with improved instructions. In case the issue is solved and confirmed by @dbinev I'd close the issue.

**Comment by dbinev** [comment] 2024-11-26 09:08
Thanks for the tip @jykahama, will try it right away...

**Comment by dbinev** [comment] 2024-11-26 09:12
Indeed it worked!
I think, we can close the issue.

**Comment by dbinev** [comment] 2024-11-28 15:31
Actually, it is still an issue.
The technology is listed there:
![{D878F736-9BB6-4E6C-B5F9-552C9BD45A17}](https://github.com/user-attachments/assets/9f0a8ac3-8f32-4932-bb77-a622f4ce63af)
but it is not possible to add any of the diagrams (nothing is available)
![{474AD17F-4E0C-450A-BD24-A7A67C3DE81E}](https://github.com/user-attachments/assets/9e80840e-d532-4d00-8ecf-c595974897f0)

**Comment by parkaneric** [comment] 2024-12-13 07:43
The XML is replaced by a zip file.
Description on landing page is updated.
Issue is closed.

**Closed as completed by parkaneric** 2024-12-13 07:43 UTC
